language: php
php:
  - 5.5
  - 5.4

script: 
#  - phpunit Test.php
  - ./.travis_scripts/build.sh

before_script:
  - chmod +x ./.travis_scripts/build.sh
  - chmod +x ./.travis_scripts/upload_to_dropbox.sh

after_success:
  - ./.travis_scripts/upload_to_dropbox.sh

