language: php
php:
  - 5.5
  - 5.4

script: 
#  - phpunit Test.php
  - ./.travis_scripts/attach_tag.sh

before_script:
  - chmod +x ./.travis_scripts/attach_tag.sh
  - chmod +x ./.travis_scripts/upload_to_dropbox.sh

after_success:
  - ./.travis_scripts/attach_tag.sh
  - ./.travis_scripts/upload_to_dropbox.sh

